/**
 * Turns `public/inkColors/*.svg` into `src/shared/inkArt.ts`.
 *
 *   node scripts/gen-ink-art.mjs
 *
 * Run it after redrawing any of the six plates. The SVGs stay the source of truth — they
 * are just not what the browser fetches, because six requests is six chances for the
 * hall's wifi to paint a colourless roster.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const IDS = ['amber', 'amethyst', 'emerald', 'ruby', 'sapphire', 'steel'];

const entries = IDS.map((id) => {
  const svg = readFileSync(`${ROOT}/public/inkColors/${id}.svg`, 'utf8');

  // Paths in document order: the first is the hexagonal plate, the rest are the symbol.
  const ds = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (ds.length < 2) throw new Error(`${id}: expected a plate plus at least one glyph path`);

  // The plate carries two of the three colours: fill = core, stroke = rim.
  const plateTag = svg.match(/<path[^>]*\sd="[^"]*"[^>]*>/)[0];
  const core = plateTag.match(/fill="(#[0-9a-f]{3,8})"/i)[1];
  const rim = plateTag.match(/stroke="(#[0-9a-f]{3,8})"/i)[1];

  // Every glyph subpath repeats the same fill; the first one is representative.
  const glyph = svg.match(/fill:(#[0-9a-f]{3,8})/i)[1];

  return { id, core, rim, glyph, plate: ds[0], paths: ds.slice(1) };
});

// The whole design leans on all six plates being the same hexagon — the empty slot on an
// unscouted row is that outline, dashed. Fail loudly rather than let one drift.
const plate = entries[0].plate;
const odd = entries.find((e) => e.plate !== plate);
if (odd) throw new Error(`${odd.id}: plate geometry differs from ${entries[0].id}`);

const q = (s) => `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

const body = entries
  .map(
    (e) => `  ${e.id}: {
    core: ${q(e.core)},
    rim: ${q(e.rim)},
    glyph: ${q(e.glyph)},
    paths: [
${e.paths.map((d) => `      ${q(d)},`).join('\n')}
    ],
  },`
  )
  .join('\n');

writeFileSync(
  `${ROOT}/src/shared/inkArt.ts`,
  `import type { InkId } from '@/lib/types';

/**
 * GENERATED by \`scripts/gen-ink-art.mjs\` from \`public/inkColors/*.svg\`. Redraw the SVGs
 * and re-run the script; do not edit this file.
 *
 * Each ink is the same pointy-top hexagonal plate — filled \`core\`, stroked \`rim\` — with
 * its symbol laid on top in \`glyph\`. Those three colours are also the app's entire
 * chromatic range: the chrome around them is graphite and bone, so nothing on screen
 * competes with a player's deck.
 */
export interface InkArt {
  /** Subpaths of the symbol itself, drawn over the plate. */
  paths: string[];
  /** Plate fill — the ink at its deepest. */
  core: string;
  /** Plate outline — the ink at full saturation. */
  rim: string;
  /** Symbol colour — the ink lightened until it carries on its own plate. */
  glyph: string;
}

/** The hexagon every ink shares. Also the empty slot on a row nobody has scouted yet. */
export const INK_PLATE = ${q(plate)};

/** Tight crop around the plate and its 8-unit stroke, plus air so a corner never clips. */
export const INK_VIEWBOX = '18 6 164 188';

/** Plate width ÷ height. Sizes are stated as heights and the width follows. */
export const INK_RATIO = 164 / 188;

export const INK_ART: Record<InkId, InkArt> = {
${body}
};
`
);

console.log(
  entries
    .map((e) => `${e.id.padEnd(9)} core ${e.core}  rim ${e.rim}  glyph ${e.glyph}  ${e.paths.length} path(s)`)
    .join('\n')
);
